larhud/urls.py
from django.contrib import admin
from django.urls import path
from nuvem import urls as nuvem_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(nuvem_urls)),
    path('admin/', admin.site.urls),
    path('nuvem/', include(nuvem_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nuvem/urls.py
from django.urls import path
from .views import new_doc
from .views import nuvem, transcribe, NuvemUploadView, NuvemUploadCompleteView

urlpatterns = [
    path('', new_doc, name="new_doc"),
    path('nuvem/<int:id>', nuvem, name="nuvem"),
    path('transcribe/', transcribe, name="transcribe"),
    path('nuvem-upload/', NuvemUploadView.as_view(), name="nuvem_upload"),
    path('nuvem-upload-completo/', NuvemUploadCompleteView.as_view(), name="nuvem_upload_completo"),
]

nuvem/models.py
import os
import glob
from django.db import models
from django.conf import settings
from django.utils.html import mark_safe
from django.dispatch import receiver
from django.db.models.signals import *
from wordcloud import WordCloud

TYPES = [
    ('simple_text', 'Texto Simples'),
    ('keywords', 'Palavras Chaves'),
]

TYPES_LANG = [
    ('pt', 'Português'),
    ('es', 'Espanhol'),
    ('en', 'Inglês'),
]

TYPES_FONT = [
    ('Carlito-Regular.ttf', 'Carlito'),
    ('Comfortaa Bold.ttf', 'Comfortaa-Bold'),
    ('Cooper Regular.ttf', 'Cooper'),
    ('Lato-Regular.ttf', 'Lato-Regular'),
    ('Poppins-Regular.ttf', 'Poppins'),
    ('Lobster-Regular.ttf','Lobster')
]


class Documento(models.Model):
    nome = models.CharField('Nome do(a) pesquisador(a)', max_length=60)
    email = models.EmailField(max_length=50)
    arquivo = models.FileField('Arquivo em PDF ou Texto', upload_to='output', max_length=200)
    language = models.CharField('Linguagem', choices=TYPES_LANG, max_length=5, null=True, blank=True)
    tipo = models.CharField(max_length=12, choices=TYPES, null=True, blank=True)
    imagem = models.ImageField('Imagem Modelo', upload_to='modelo', max_length=200, null=True, blank=True)
    descritivo = models.TextField('Descritivo da Nuvem', null=True, blank=True)
    stopwords = models.TextField('Stopwords Extras', null=True, blank=True)
    chave = models.CharField('Chave de Acesso', max_length=20, null=True, blank=True)
    cores = models.BooleanField(default=False)
    colormap = models.CharField('Mapa de Cores', max_length=20, default='viridis')
    font_type = models.CharField('Font Type', max_length=40, choices=TYPES_FONT, null=True, blank=True)
    consolidado = models.BooleanField(default=False)
    status = models.CharField(choices=(('A', 'Aberto'), ('P', 'Programado'), ('F', 'Finalizado'),
                                       ('E', 'Com erro')), max_length=1, default='A')

    @property
    def texto(self):
        filename = os.path.splitext(os.path.basename(self.arquivo.path))[0]
        return os.path.join(settings.MEDIA_URL, 'output', filename+'.dedup')

    @property
    def csv(self):
        filename = os.path.splitext(os.path.basename(self.arquivo.path))[0]
        return os.path.join(settings.MEDIA_URL, 'output', filename + '.csv')

    @property
    def img(self):
        filename = os.path.splitext(os.path.basename(self.arquivo.path))[0]
        return os.path.join(settings.MEDIA_URL, 'output', filename + '.png')

    @property
    def tamanho(self):
        filesize = os.path.getsize(self.arquivo.path)
        kb_size = round(filesize / 1024)
        return str(kb_size) + 'KB'

    def pdf_link(self):
        return mark_safe('<a class="grp-button" href="/nuvem/nuvem/%s?chave=%s">Gerar Nuvem</a>' % (self.id, self.chave))

    pdf_link.short_description = 'Nuvem'


@receiver(post_delete, sender=Documento)
def deletar_arquivos(sender, instance, **kwargs):
    prefix = os.path.splitext(instance.arquivo.path)[0]
    for filePath in glob.glob(prefix + '.*'):
        os.remove(filePath)

nuvem/forms.py
import os

from django import forms
from django.conf import settings
from django.forms import ModelForm
from django.utils.safestring import mark_safe

from .models import Documento, TYPES, TYPES_LANG, TYPES_FONT


class DocumentoForm(ModelForm):
    tipo = forms.ChoiceField(label='Tipo de Arquivo', choices=TYPES, required=True)
    font_type = forms.ChoiceField(label='Tipo da Fonte', choices=TYPES_FONT, required=True)
    chave = forms.CharField(label='Chave de Acesso (Opcional)', required=False)

    class Media:
        js = ('js/validation.js',)

    class Meta:
        model = Documento
        fields = ['nome', 'email', 'tipo', 'font_type', 'arquivo', 'chave']

    def clean_arquivo(self):
        files = self.files.getlist('arquivo')
        tipo = self.cleaned_data.get('tipo')

        for file in files:
            extension = os.path.splitext(file.name)[1]
            if extension != '.txt' and extension != '.pdf':
                self.add_error('arquivo',
                               'Extensão %s do arquivo %s inválida. Somente arquivos de textos e PDF '
                               'são permitidos.' % (extension, file.name))

            if tipo == 'keywords' and extension != '.txt':
                self.add_error('arquivo', 'Extensão %s do arquivo %s inválida. Somente arquivos .txt '
                                          'são permitidos para esse tipo de arquivo.' % (extension, file.name))

            return self.cleaned_data.get('arquivo')


colormap_url = 'https://www.kaggle.com/code/niteshhalai/wordcloud-colormap'


class LayoutForm(forms.Form):
    language = forms.ChoiceField(label='Selecione o idioma:', choices=TYPES_LANG, required=True)
    font_type = forms.ChoiceField(label='Selecione a fonte:', choices=TYPES_FONT, required=True)
    colormap = forms.CharField(
        label='Mapa de Cores', required=False,
        help_text=mark_safe(f"Visualize os mapas possíveis <a href='{colormap_url}' target='_blank'>aqui</a>"))
    descricao = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}),
                                label='Descrição:', required=False)
    stopwords = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}),
                                label='Adicione mais stopwords (separando-as por ","):', required=False)
    # min_size = forms.IntegerField(widget=forms.IntegerField(), label='Frequência mínima:', initial=2)
    imagem = forms.FileField(widget=forms.FileInput(
        attrs=(
            {'class': 'custom-file-input', 'id': 'inputGroupFile01', 'aria-describedby': 'inputGroupFileAddon01'}
        )), label='Imagem:', required=False)
    cores = forms.BooleanField(widget=forms.CheckboxInput,
                               label='Utilizar as cores da Imagem', required=False)


class UploadForm(DocumentoForm):
    arquivo = forms.FileField(label='Arquivo em PDF ou Texto', widget=forms.FileInput(attrs={'accept': '.txt,.pdf'}))

    class Meta(DocumentoForm.Meta):
        fields = ['arquivo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name in ['tipo', 'font_type', 'chave']:
            self.fields[name].widget = forms.HiddenInput()
            self.fields[name].required = False

nuvem/views.py
import os
import sys
import uuid
import json
import urllib
import detectlanguage
import numpy as np
from PIL import Image
from django.http import HttpResponseRedirect

from django.shortcuts import render

from threading import Thread
from datetime import datetime

from nuvem.apps import normalize_colormap
from nuvem.models import Documento
from nuvem.forms import DocumentoForm, LayoutForm
from django.conf import settings
from gerador.genwordcloud import generate, generate_words
from django.contrib import messages
from gerador.pdf2txt import pdf2txt

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(os.path.dirname(SCRIPT_DIR))
detectlanguage.configuration.api_key = settings.API_KEY_LANGUAGE


def home(request):
    return render(request, 'home.html')


class ProcessThread(Thread):
    def __init__(self, document_id):
        Thread.__init__(self)
        self.document_id = document_id
        self.started = datetime.now()

    def run(self):
        doc_base = Documento.objects.get(id=self.document_id)
        if doc_base.consolidado:
            extra_file = open(doc_base.arquivo.path, 'w+')
            for doc in Documento.objects.filter(chave=doc_base.chave).exclude(id=self.document_id):
                filename, extensao = os.path.splitext(doc.arquivo.path)
                if extensao == '.pdf':
                    pdf2txt(doc.arquivo.path)
                    print('PDF gerado %s' % doc.arquivo.path)
                with open(filename + '.txt', 'r') as f:
                    extra_file.write(f.read())
                    extra_file.write('\n')
            extra_file.close()
            doc_base.status = 'F'
            doc_base.save()
        else:
            pdf2txt(doc_base.arquivo.path)
            doc_base.status = 'F'
            doc_base.save()

        finished = datetime.now()
        duration = (finished - self.started).seconds
        print("%s thread started at %s and finished at %s in %s seconds" %
              (self.document_id, self.started, finished, duration))


def custom_redirect(url_name, *args, **kwargs):
    from django.urls import reverse
    url = reverse(url_name, args=args)
    params = urllib.parse.urlencode(kwargs)
    return HttpResponseRedirect(url + "?%s" % params)


def nuvem(request, id):
    documento = Documento.objects.get(pk=id)
    if documento.status != 'F':
        return render(request, 'nuvem.html', {'allow_edit': False, 'doc': documento})

    nome_arquivo = documento.arquivo.path
    prefix, file_extension = os.path.splitext(nome_arquivo)  # prefix = (root,ext)
    if not os.path.exists(prefix + '.txt'):  # caso nao seja um arquivo txt
        pdf2txt(documento.arquivo.path)  # vamos converter de pdf para txt

    nome_arquivo = prefix + '.txt'
    # if os.path.exists(prefix + '.dedup'):                       #caso exista um arquivo.dedup
    #    os.rename(prefix + '.dedup', prefix + key + '.dedup')   #renomear usando a key

    numero_linhas = 50
    if not documento.language:
        try:
            num_linha = 0
            trecho = ''
            with open(nome_arquivo) as f:
                while num_linha < 50:
                    linha = f.readline().lower().strip()
                    if len(linha) > 3:
                        trecho += linha + ' '
                        num_linha += 1
        except UnicodeDecodeError as erro:
            linhas = open(nome_arquivo, encoding='ISO-8859-1').read().lower().split('.')[ 0:numero_linhas ]
            trecho = ' '.join([ ('' if len(linha) < numero_linhas else linha) for linha in linhas ])
        lang_detect = detectlanguage.detect(trecho)
        if len(lang_detect) > 0:
            precisao = lang_detect[0]['confidence']
            if precisao > 5:
                documento.language = lang_detect[0]['language']
                documento.save()

    form = LayoutForm(request.POST or None, request.FILES or None,
                      initial={
                          'descricao': documento.descritivo or None,
                          'font_type': documento.font_type,
                          'cores': documento.cores,
                          'colormap': documento.colormap,
                          'language': documento.language
                      })

    allow_edit = documento.chave and request.GET.get('chave') and documento.chave == request.GET.get('chave')

    # Confere se o mapa gravado realmene existe
    documento.colormap = normalize_colormap(documento.colormap)

    if request.POST:
        if form.is_valid():
            documento.descritivo = form.cleaned_data.get('descricao')
            colormap = form.cleaned_data.get('colormap')
            documento.colormap = normalize_colormap(colormap)
            if colormap != documento.colormap:
                messages.warning(request, 'O mapa de cores não foi encontrado. Verifique se não houve erro de digitação')
            if form.cleaned_data.get('imagem'):
                documento.imagem = form.cleaned_data.get('imagem')
                documento.cores = form.cleaned_data.get('cores')
            else:
                documento.imagem = None
                documento.cores = False

            documento.font_type = form.cleaned_data.get('font_type')
            documento.stopwords = form.cleaned_data.get('stopwords')
            documento.language = form.cleaned_data.get('language')
            documento.save()
            messages.success(request, 'Alteração salva com sucesso.')

    mask = None
    channel = 0
    if documento.imagem:
        try:
            image = Image.open(documento.imagem)
            channel = len(image.split())
            mask = np.array(image)
        except:
            messages.error(request, 'Não foi possivel usar a imagem como mascára, por favor selecione outra.')

    font_type = documento.font_type or 'Carlito-Regular.ttf'
    if not os.path.exists(os.path.join(settings.FONT_PATH, font_type)):
        messages.error(request,
                       'A fonte escolhida não foi encontrada na pasta. Por favor verificar a instalação da fonte.')

    # Fix error: Not Implement methods para imagens com menos de 3 canais.
    if channel >= 3 or not documento.cores:
        color = documento.cores
    else:
        messages.error(request, 'Não foi possivel obter as cores dessa imagem, '
                                'pois ela possui somente %s %s.' % (channel, 'canais' if channel > 1 else 'canal'))
        color = False

    if documento.tipo == 'keywords':
        imagem = generate_words(nome_arquivo, documento.language, mask, color, font_type,
                                documento.colormap)
    else:
        imagem = generate(nome_arquivo, documento.stopwords, documento.language, mask, color, font_type,
                          documento.colormap)

    contexto = {
        'allow_edit': allow_edit,
        'form': form,
        'doc': documento,
        'nuvem': imagem
    }

    return render(request, 'nuvem.html', contexto)


def new_doc_test_size(request):
    form = DocumentoForm(request.POST or None, request.FILES or None)
    recaptcha = getattr(settings, "GOOGLE_RECAPTCHA_PUBLIC_KEY", None)

    if form.is_valid():
        if recaptcha:
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            result = result['success']
        else:
            result = True

        if result:
            post = form.save(commit=False)
            # A hash key serve para identificar os arquivos gerados em um mesmo processamento
            if not post.chave:
                hash_key = str(uuid.uuid4())[:20]
            else:
                hash_key = post.chave
            if request.FILES:
                # Verifica se todos os arquivos são PDF ou TXT antes de gravar
                for f in request.FILES.getlist('arquivo'):
                    filename, extensao = os.path.splitext(str(f))
                    if not (extensao == '.pdf' or extensao == '.txt'):
                        messages.error(request,
                                       'Extensão do arquivo %s inválida. Por favor selecione arquivos .txt ou .pdf' %
                                       filename)
                        return render(request, 'person_form.html', {'form': form, 'recaptcha': recaptcha})

                docs = []
                total_size = 0
                for f in request.FILES.getlist('arquivo'):
                    filename, extensao = os.path.splitext(str(f))
                    doc = Documento.objects.create(nome=post.nome, email=post.email, arquivo=f, tipo=post.tipo,
                                                   font_type=post.font_type, chave=hash_key)
                    docs.append(doc)
                    total_size += os.path.getsize(doc.arquivo.path)

                # se houver mais de um arquivo ou se o arquivo for PDF e maior que 5Mb,
                # a conversão será feita via thread
                if len(docs) > 1 or post.chave:
                    extra_filename = 'output/' + hash_key + '.txt'
                    try:
                        doc_final = Documento.objects.get(chave=hash_key, consolidado=True)
                    except Documento.DoesNotExist:
                        doc_final = Documento.objects.create(
                                        nome=post.nome, email=post.email, arquivo=extra_filename,
                                        tipo=post.tipo, chave=hash_key,
                                        font_type=post.font_type, status='P', consolidado=True)

nuvem/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Nuvem de Palavras Larhud</title>
    <link rel="stylesheet" href="/static/style.css">
    {% block extrastyle %}{% endblock %}
</head>
<body>
    <header class="topo">
        <img src="/static/Logo.png" alt="" height="70">
        <h1 class="my-3">{% block title %}{% endblock %}</h1>
    </header>
    <div class="container">
        {% block main %}
        {% endblock %}
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $('#id_arquivo').attr("multiple","true");
    })
</script>
{% block extrascript %}{% endblock %}
</body>
</html>

nuvem/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Nuvem de Palavras Larhud</title>
</head>
<body>
    <h1 class="home"></h1>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}

        <button type="submit">Salvar</button>
    </form>
</body>

nuvem/templates/nuvem.html
{% extends 'base.html' %}
{% block title %}Gerador de Nuvem de Palavras{% endblock %}
{% load bootstrap %}
{% block extrastyle %}
    <style>
        input#inputGroupFile01{
            margin-top: 5px;
        }
        .form-group{
            margin-top: 10px;
        }
        .modal-header{
            margin-bottom: 16px;
        }
        label.custom-file-label {
            margin-top: 6px;
        }
    </style>
{% endblock %}
{% block main %}
    {% if messages %}
        {% for message in messages %}
              {% if message.tags %}<div class="alert alert-{% if message.tags == 'error' %}danger{%else%}{{message.tags}}{%endif%} alert-dismissible fade show mt-3" role="alert">{{message}}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>{% endif %}
        {% endfor %}
    {% endif %}

    {% if doc.status == 'F' %}
        <h2 style="margin-top: 20px">
            {% if doc.descritivo %}
                {{ doc.descritivo }}
            {% else %}
                Nuvem gerada com sucesso!!
            {% endif %}
        </h2>
        <img src="{{ nuvem }}" alt="" height="500">
        <br/>
        <p>Usuário: {{ doc.nome}}</p>
        <p>Linguagem reconhecida: {{ doc.language }}</p>
        <p><a href="{{ doc.texto}}">Arquivo Texto já sem as stopwords</a></p>
        <p><a href="{{ doc.csv }}">Arquivo de Frequência</a></p>

        {% if allow_edit %}
        <div style="margin-bottom: 10px">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Alterar Layout</button>
        </div>
        {% endif %}
    {% elif doc.status == 'E' %}
        <div style="margin-top: 10px">
        <h2>Ocorreu um erro ao gerar a nuvem :( <a href="{{ doc.texto }}">Clique aqui para visualizar o log de erro</a></h2>
        </div>
    {% else %}
        <div style="margin-top: 10px">
        <h2>Processamento em andamento.</h2>
        <a href="/nuvem/nuvem/{{ doc.id }}?chave={{ doc.chave }}">Clique aqui para atualizar a tela</a>
        <p>ou</p>
        <a href="/">Clique aqui para incluir mais arquivos.</a> Utilize a chave {{ doc.chave }}
        </div>
    {% endif %}

  {% if allow_edit %}
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Layout</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            {{ form.language|bootstrap }}
            {{ form.font_type|bootstrap }}
          </div>
          <div class="form-group">
            {{ form.descricao|bootstrap }}
          </div>
          <div class="form-group">
            {{ form.stopwords|bootstrap }}
          </div>
          <div class="form-group">
            {{ form.colormap|bootstrap }}
          </div>
          <br/>
          <div class="input-group">
              <div class="custom-file">
                {{ form.imagem|bootstrap }}
                <label class="custom-file-label" for="inputGroupFile01" id="id_label_img">{% if doc.imagem %}{{ doc.imagem.name }}{% else %}Escolha uma Imagem (opcional){% endif %}</label>
              </div>
          </div>
          {{ form.cores|bootstrap }}
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">Enviar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{%endblock%}
{% block extrascript %}
    <script>
        document.querySelector('#inputGroupFile01').addEventListener('change', e => {
            let checkbox = document.querySelector('#id_cores');
            let label = document.getElementById('id_label_img')
            if (e.target.value){
                label.innerText =e.target.files[0].name;
            }else{
                label.innerText = 'Escolha uma Imagem';
            }
            checkbox.checked = !!e.target.value;
        });
    </script>

{% endblock %}

nuvem/templates/person_form.html
{% extends 'base.html' %}
{% load bootstrap static %}
{% block title %}Gerador de Nuvem de Palavras{% endblock %}
{% block main %}
<style>
    span.help-block {
        color: red;
        display: block;
        font-size: 14px;
    }
</style>
     {% if messages %}
            {% for message in messages %}
              {% if message.tags %}<div class="alert alert-{% if message.tags == 'error' %}danger{%else%}{{message.tags}}{%endif%} alert-dismissible fade show mt-3" role="alert">{{message}}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>{% endif %}
            {% endfor %}
    {% endif %}
<div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">
            <br/>
            <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    {{ form.media }}
                    {% if recaptcha %}
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div class="g-recaptcha" data-sitekey="{{ recaptcha }}" ></div>
                    {% endif %}
                    <br><button type="submit" class="btn btn-info">Enviar</button>
            </form>
        </div>
   <div class="col-sm-2"></div>
</div>
<div class="row">
   <div class="col-sm-2"></div>
   <div class="col-sm-8">
    <br/>
    <p>Como usar a nuvem:</p>
    <ul>
        <li>Indique o seu nome e email para que a equipe do Larhud possa entrar em contato com você (seus dados só serão utilizados para o propósito exclusivo de comunicação sobre a nuvem que você gerou)</li>
        <li>Selecione um <b>ou vários arquivos </b> no formato PDF ou TXT</li>
        <li>A geração da nuvem de palavras consegue identificar qual o idioma dos arquivos e remove stopwords baseada na linguagem identificada. Assim, para que a nuvem faça sentido, envie os arquivos em um único idioma</li>
        <li>Cabeçalhos e rodapés de artigos já são identificados e removidos automaticamente</li>
        <li>A chave de acesso pode ficar em branco. Ela serve apenas caso você queira adicionar novos arquivos a um processamento já existente</li>
        <li>Caso tenha dúvidas ou sugestões, envie email para <a href="mailto:josir@irdx.com.br">josir@irdx.com.br</a></li>
    </ul>
   </div>
   <div class="col-sm-2"></div>
</div>

{% endblock %}